tdd_s7/urls.py
from django.urls import path, include
from .views import index, confirmation

urlpatterns = [
    path('', index, name='index'),
    path('confirmation/', confirmation, name='confirmation'),
]

tdd_s7_draft/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tdd_s7.urls'))
]

tdd_s7/models.py
from django.db import models
from django.forms import ModelForm

# Create your models here.

class Status(models.Model):
    name = models.CharField(max_length=30)
    status = models.TextField()

    def __str__(self):
        return self.name

tdd_s7/forms.py
from .models import Status
from django.forms import ModelForm, TextInput, Select

class Status_Form(ModelForm):
    class Meta:
        model = Status
        fields=[ 'name','status']
        widgets = {'name': TextInput(attrs={'class': 'form-control'}),'status': TextInput(attrs={'class': 'form-control'}),}

tdd_s7/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, request, HttpResponse
from .forms import Status_Form
from .models import Status

# Create your views here.
def index(request):
    status = Status.objects.all()
    form= Status_Form()
    if (request.method=='POST'):
        form = Status_Form(request.POST)
    else:
        form= Status_Form()
    return render(request, 'index.html',{'form': form, 'status': status})

def confirmation(request):
    if request.method == 'POST':

        if 'submit' in request.POST:
            form = Status_Form(request.POST)
            if form.is_valid():
                name = form.cleaned_data['name']
                status = form.cleaned_data['status']
                return render(request, 'confirmation.html', {'name': name, 'status': status})
        elif 'continue' in request.POST:
            form = Status_Form(request.POST)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect('/')
        else:
            return HttpResponseRedirect('/')

    return render(request, 'confirmation.html', {'name': "", "status": ""})

tdd_s7/templates/confirmation.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Confirmation</title>
</head>
<body>
<h3 id="name">Name: {{ name }}</h3>
<h3 id="status">Status: {{ status }}</h3>

<form action="{% url 'confirmation' %}" method="POST">
    {% csrf_token %}
    <input type="hidden" name="name" id="id_name" value="{{ name }}">
    <input type="hidden" name="status" id="id_status" value="{{ status }}">
    <br>
    <p>Are you sure you want to post this status</p>
    <button id="back">Cancel</button>
    <input class="submit_button" type="Submit" name="continue" value="Submit Status"/>
</form>
</body>
</html>

tdd_s7/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>

<h1>
    Hello, how are you?
</h1>

<div>
    <form method="POST" action="{% url 'confirmation' %}">
        {% csrf_token %}
        <label>Name:</label>
        {{ form.name }}
        <label>Status:</label>
        {{ form.status }}
        <br>
        <button type="submit" name="submit">Submit</button>
    </form>
</div>


<table style="width: 100%; border: 1px solid black;">
    <thead style="width: 100%;border: 1px solid black; background-color: grey;">
    <th style="text-align: center;">Name</th>
    <th style="text-align: center;">Status</th>
    </thead>
    {% for stat in status %}
    <tr style="background-color: honeydew;">
        <th style="text-align: center;">{{ stat.name }}</th>
        <th style="text-align: center;">{{ stat.status }}</th>
    </tr>
    {% endfor %}
</table>


<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>
</html>